name: supabase_gen
description: A Dart package that generates Flutter repositories and models from Supabase database
version: 1.0.0
repository: https://github.com/albaraazain/supabase_gen

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.4.0
  postgres: ^2.6.1
  recase: ^4.1.0
  path: ^1.8.3
  yaml: ^3.1.1
  logging: ^1.1.1
  supabase_flutter: ^2.8.4
  
dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
