name: supabase_gen
description: A Dart package that generates Flutter repositories and models from Supabase database. Compatible with latest Supabase Flutter SDK. Requires supabase_flutter ^2.8.4 as a dependency in your app.
version: 1.6.0
repository: https://github.com/albaraazain/supabase_gen

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.4.2
  postgres: ^3.5.4
  recase: ^4.1.0
  path: ^1.9.0
  yaml: ^3.1.2
  logging: ^1.2.0
  http: ^1.2.0
  dio: ^5.4.0  # For making HTTP requests to Supabase REST API
  riverpod_annotation: ^2.6.1
  supabase_flutter: ^2.9.0
  flutter_riverpod: ^2.6.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2