name: supabase_gen
description: A Dart package that generates Flutter repositories and models from Supabase database. Compatible with latest Supabase Flutter SDK.
version: 1.0.1
repository: https://github.com/albaraazain/supabase_gen

environment:
  sdk: ^3.7.0

dependencies:
  args: ^2.4.2
  postgres: ^3.5.4
  recase: ^4.1.0
  path: ^1.9.0
  yaml: ^3.1.2
  logging: ^1.2.0
  
dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.2

# Note: Your app needs these peer dependencies
peer_dependencies:
  supabase_flutter: ^2.3.0
