name: supabase_gen_test
description: A test app for the supabase_gen query builder.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^1.10.0
  flutter_riverpod: ^2.3.6
  go_router: ^7.1.1
  cupertino_icons: ^1.0.5
  intl: ^0.18.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true