# Remote database configuration - uncomment and fill in details to use remote mode
database:
  connection_type: remote
  supabase_url: https://ropservice.duckdns.org
  supabase_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJzZXJ2aWNlX3JvbGUiLAogICAgImlzcyI6ICJzdXBhYmFzZS1kZW1vIiwKICAgICJpYXQiOiAxNjQxNzY5MjAwLAogICAgImV4cCI6IDE3OTk1MzU2MDAKfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q
  database: postgres  # Database name is still required even for remote connection


generation:
  output_directory: ../rop/lib/generated/
  model_prefix: ''
  model_suffix: Model
  repository_suffix: Repository
  
  # Exclude generated columns from model serialization
  exclude_generated_columns: true
  
  # Custom column exclusions for specific tables
  column_exclusions:
    driver_locations:
      - location_point  # Generated column that should not be in toJson()
  
  exclude_tables: 
    # Exclude system schemas
    - '_realtime.*'
    - 'auth.*'
    - 'net.*'
    - 'pgsodium.*'
    - 'realtime.*'
    - 'storage.*'
    # - 'supabase_functions.*'
    - 'vault.*'
    # Exclude views and system tables from public schema
    - 'public.*_view'
    # Exclude postgis system tables
    - 'spatial_ref_sys'
    - 'geography_columns'
    - 'geometry_columns'
    - 'spatial_ref_sys'
    
    
  include_tables: 
    - 'payment_notifications'  # Include payment_notifications table
  
  generate_for_all_tables: false  # Only generate for explicitly included tables
  use_null_safety: true

  # NEW: Provider generation options
  providers:
    # Set to true to enable generation of Riverpod providers
    generate: true
    
    # Provider naming conventions
    suffix: Provider
    
    # State management options
    type: riverpod  # Currently only riverpod is supported
    
    # Use AppException class for error handling
    # If true, imports AppException from core/errors/app_exception.dart
    use_app_exception: true
    
    # Whether providers should use keepAlive to persist state
    # When set to false, providers will be auto-disposed when no longer used
    use_keep_alive: false
    
    # Whether to auto-invalidate providers on data changes
    # When true, notifiers will refresh their state after CRUD operations
    invalidate_on_change: true
    
    # Generate AsyncValueWidget for easy UI consumption
    # Creates a standard widget for handling async states in shared/widgets/
    generate_async_value_widget: true


  # RPC function generation options
  rpc_functions:
    # Enable RPC service generation
    generate: true
    
    # Function-specific type overrides
    type_overrides:
      get_nearby_online_drivers:
        return_type: 'List<dynamic>'
        description: 'Returns an array of nearby online drivers with vehicle info'
    
    # Enable RPC model generation for complex return types
    generate_models: true
    
    # Enable RPC provider generation (if providers are enabled)
    generate_providers: true
    
    # Enable RPC documentation generation
    generate_documentation: true
    
    # RPC service naming conventions
    service_suffix: RpcService
    model_suffix: Result
    
    # Function grouping strategy: 'category', 'schema', or 'alphabetical'
    grouping_strategy: category
    
    # Function categories for OnYourWay ride-sharing platform
    categories:
      # Trip and ride management functions
      trips: ['create_scheduled_trip', 'start_trip', 'complete_trip', '*trip*']
      
      # Ride requests and booking functions  
      bookings: ['create_ride_request', 'accept_ride_request', 'reject_ride_request', 
                'create_booking_from_request', 'create_instant_ride_booking', 
                'cancel_booking', 'confirm_passenger_pickup', '*booking*', '*request*']
      
      # Instant ride specific functions
      instant_rides: ['*instant_ride*', 'match_driver_to_instant_ride', 
                     'accept_instant_ride_request', 'reject_instant_ride_request',
                     'cleanup_expired_instant_ride_requests']
      
      # Payment and financial functions
      payments: ['process_payment', 'calculate_instant_ride_fare', '*payment*', 
                '*fare*', '*price*', '*cost*']
      
      # Review and rating functions
      reviews: ['submit_review', '*review*', '*rating*']
      
      # Driver and location functions
      drivers: ['get_nearby_online_drivers', 'find_available_drivers_for_instant_ride',
               '*driver*', '*location*']
      
      # Statistics and analytics functions
      analytics: ['get_user_trip_stats', 'get_current_surge_multiplier', '*stats*', 
                 '*analytics*', '*metrics*', '*report*']
      
      # Search and discovery functions
      search: ['get_nearby_trips', 'search_*', 'find_*', '*lookup*', 'filter_*']
      
      # User and authentication functions (for future use)
      auth: ['login_*', 'register_*', 'verify_*', '*_auth*', '*user*']
      
      # Admin and system functions
      admin: ['*_admin*', 'manage_*', '*_system*', '*_config*', 'cleanup_*']
    
    # Functions to include (empty = include all)
    include_functions: []
    
    # Functions to exclude (schema introspection, utility, and remaining PostGIS functions)
    exclude_functions: [
      # Schema introspection functions (used by generator, not for app)
      'get_function_details',
      'get_generated_columns', 
      'get_rpc_function_details',
      'get_rpc_function_parameters',
      'get_table_columns',
      'get_table_constraints',
      'get_table_indexes',
      'get_table_triggers',
      'get_table_type',
      'get_function_simple_info',
      'list_rpc_functions',
      'list_tables',
      
      # Remaining PostGIS functions
      'addgeometrycolumn',
      'get_proj4_from_srid',
      
      # Utility functions
      'update_expired_requests'
    ]
    
    # Logging and caching settings
    enable_logging: true
    enable_caching: true