name: supabase_gen_test_app
description: A new Flutter project using Supabase.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.0.0
  provider: ^6.0.5
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  logger: ^2.5.0
  flashy_tab_bar2: ^0.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - .env
    - assets/images/
    - assets/animations/