name: supabase_gen_test_app
description: "A new Flutter project to test supabase_gen package"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  supabase_flutter: ^2.3.4
  provider: ^6.1.2
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  supabase_gen: ^1.0.1
  build_runner: ^2.4.15

flutter:
  uses-material-design: true 